apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: stock
  name: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stock
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: stock
    spec:
      containers:
        - image: stock
          name: rso-stock
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
